### ISSUE TITLE
Can you elaborate on buildSrc vs. Composite Build for convention plugins? 

### ISSUE THREAD

**Issue by asaikali** [jjohannes/idiomatic-gradle#16]
I have always used `buildSrc` for my convention plugins, but I have not see you use it any of your demos / videos. What are the pros and cons of `buildSrc` as the place for convention plugins.

**Comment by jjohannes** [comment]
Hi @asaikali. That's a question that comes up regularly. In short, `buildSrc` is essentially the same as using a custom included build in pluginManagement (`gradle/plugins` in this repo) just that you cannot change the location. It also works in older Gradle versions. That's why it exists: it's an older feature.

I'll repeat what I posted [here](https://www.youtube.com/watch?v=N95YI-szd78&lc=UgymlLb_xLJ6VEoYvYZ4AaABAg).

----

Clarification about where to put your own convention plugins
In my videos, I typically put them in a separate folder to emphasize that it is a separate Gradle build:

```
pluginManagement {
    includeBuild("../my-build-logic")
}
```

In a single repository setup, you typically put them inside the folder hierarchy of your project. I suggest a subfolder of 'gradle' which you often already have:

```
pluginManagement {
    includeBuild("gradle/plugins")
}
```

In older Gradle versions, this was not supported and you always needed to use buildSrc inside your project:

```
pluginManagement {
    // includeBuild("buildSrc") -- Gradle does this automatically as soon as 'buildSrc/build.gradle' exists
}
```
