### ISSUE TITLE
Build-logic project clean uses different Gradle version

### ISSUE THREAD

**Issue by hrach** [jjohannes/idiomatic-gradle#5]
Hello, we are using patterns based on this repository and we have met weird issue when cleaning through Android studio.

It runs cleans for both projects and the build-logic project clean fail with error resulting from the fact it uses some older Gradle version.

Currently, it is a `Using dependency catalogs requires the activation of the matching feature preview.` error. Otherwise, building the app normally works.

Do you have any idea why a different Gradle version is used? Thank you.

![](https://user-images.githubusercontent.com/284263/168989935-57c57aa4-8909-4192-9267-45c206ab3aac.png)

**Comment by hrach** [comment]
The error is 
```
Settings file 'D:\xxx\android\build-logic\settings.gradle.kts' line: 3

Using dependency catalogs requires the activation of the matching feature preview.
See the documentation at https://docs.gradle.org/7.1/userguide/platforms.html#sub:central-declaration-of-dependencies
```

So basically it seems that Gradle 7.1 is used instead of 7.4.2

**Comment by jjohannes** [comment]
Hi @hrach. That's a known issue, which I think is fixed in newer IntelliJ versions - I don't see it anymore in IDEA 2022.1.1.

Here, Android Studio treats the included _build-logic_ build as a separate build. And since it is configured to look for the Wrapper in the build, it looks for the Wrapper in `build-logic/gradle/wrapper/gradle-wrapper.properties`. Since there is non, it falls back to the Gradle version packaged in Android Studio. Which happens to be `7.1` in your case.

There are two workarounds I know of to make it work in your Android Studio version:
- Configure a Gradle installation in the Preferences. For that you would have to install `7.4.2` explicitly and point Android Studio at it (not a very nice solution if you use the wrapper).
- Duplicate the `gradle-wrapper.properties` to the `build-logic/gradle/wrapper/`. I think it's enough to have the `distributionUrl` entry in the duplicate as that is the only thing the Ide looks at. I think that's the best solution until this is fixed, but you'll have to remember updating that copy each time you upgrade the Gradle version.

**Comment by hrach** [comment]
Oh, thanks a lot. ❤️ it didn't crossed my mind that this is an AS issue, I was searching Gradle issues only.
